apiVersion: v1
kind: Namespace
metadata:
  name: chat-app
  labels:
    app: chat-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat-app-sa
  namespace: chat-app
  labels:
    app: chat-app
  annotations:
    azure.workload.identity/client-id: "WORKLOAD_IDENTITY_CLIENT_ID_PLACEHOLDER"
