apiVersion: v1
kind: Namespace
metadata:
  name: chat-app
  labels:
    app: chat-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat-app-sa
  namespace: chat-app
  labels:
    app: chat-app
  annotations:
    azure.workload.identity/client-id: "80b6071d-28e9-4329-affb-436945a91b30"
