apiVersion: v1
kind: Service
metadata:
  name: chat-app
  namespace: chat-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
